Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.synced_folder "shared/", "/shared"
  config.vm.define "vagrant-ubuntu"
  config.vm.provision "shell",
    inline: "touch /home/vagrant/.hushlogin"
  config.trigger.after :up do |trigger|
    trigger.name = "Finished Message"
    trigger.info = "Don't forget to run v vagrant-ubuntu to add it to ssh config!"
  end
  config.vm.provider "virtualbox" do |v|
    v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
  end
end
